### ISSUE TITLE
Allow a user to specify a list of repos instead of passing one via cli args

### ISSUE THREAD

**Issue by frodopwns** [drud/prepo#2]
This could look something like this:

```
repos:
  - org: drud
    repo: prepo
labels:
  - name: needs docs
    color: 5319e7
  - name: needs manual testing
    color: fbca04
```

prepo would then loop through the repos applying the labels to each one
