### ISSUE TITLE
Add other useful things to prepo.yaml like teams and milestones

### ISSUE THREAD

**Issue by frodopwns** [drud/prepo#4]
Would look something like:

```
labels:
  - name: needs docs
    color: 5319e7
  - name: needs manual testing
    color: fbca04
milestones:
  - name: 0.1.0
  - name: 0.2.0
  - name: 0.3.0
teams:
  - name: devs
  - name: pms
  - name: qa
```
