### ISSUE TITLE
Add a feature that allows a user to set PR/issue templates 

### ISSUE THREAD

**Issue by frodopwns** [drud/prepo#5]
could look something like this:

```
labels:
  - name: needs docs
    color: 5319e7
  - name: needs manual testing
    color: fbca04
templates:
  pr: path/to/file
  issue: path/to/file
```
